-- =====================================================================
--  V1: users table
-- ---------------------------------------------------------------------
--  Mirrors hr.zavrsni.incidentapp.user.User.
--
--  Naming: column types and lengths must match what Hibernate would have
--  generated, otherwise ddl-auto: validate refuses to start.
--
--  id            BIGINT identity         (Long + GenerationType.IDENTITY)
--  username      VARCHAR(64) UNIQUE      (length=64 in @Column)
--  password      VARCHAR(255)            (default length when none given)
--  role          VARCHAR(16)             (Role enum stored as STRING)
--  created_at    TIMESTAMPTZ             (java.time.Instant)
-- =====================================================================
CREATE TABLE users (
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    username    VARCHAR(64)              NOT NULL UNIQUE,
    password    VARCHAR(255)             NOT NULL,
    role        VARCHAR(16)              NOT NULL,
    created_at  TIMESTAMP WITH TIME ZONE NOT NULL
);
