-- =====================================================================
--  V2: incidents table
-- ---------------------------------------------------------------------
--  Mirrors hr.zavrsni.incidentapp.incident.Incident, including the
--  Phase 8 fields (incident_time, location, assigned_to_id).
--
--  Foreign keys:
--    reporter_id     -> users(id), NOT NULL  (every incident has a reporter)
--    assigned_to_id  -> users(id), NULL      (unassigned by default)
--
--  ON DELETE behaviour:
--    RESTRICT on reporter_id   — never silently lose the link to the owner.
--    SET NULL on assigned_to_id — if the assignee account is deleted, the
--                                 incident becomes "unassigned" rather than
--                                 cascading the deletion to the incident.
--
--  Indexes:
--    Postgres does NOT auto-index foreign key columns. We add indexes on
--    the FK columns and on the columns we'll filter/sort by frequently
--    (status for lists, created_at for ordering newest first).
-- =====================================================================
CREATE TABLE incidents (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    title           VARCHAR(140)             NOT NULL,
    description     TEXT,
    category        VARCHAR(16)              NOT NULL,
    severity        VARCHAR(16)              NOT NULL,
    status          VARCHAR(16)              NOT NULL,
    reporter_id     BIGINT                   NOT NULL,
    incident_time   TIMESTAMP                NOT NULL,
    location        VARCHAR(200),
    assigned_to_id  BIGINT,
    created_at      TIMESTAMP WITH TIME ZONE NOT NULL,
    updated_at      TIMESTAMP WITH TIME ZONE NOT NULL,
    resolved_at     TIMESTAMP WITH TIME ZONE,

    CONSTRAINT fk_incidents_reporter
        FOREIGN KEY (reporter_id)    REFERENCES users(id) ON DELETE RESTRICT,
    CONSTRAINT fk_incidents_assignee
        FOREIGN KEY (assigned_to_id) REFERENCES users(id) ON DELETE SET NULL
);

CREATE INDEX idx_incidents_reporter    ON incidents(reporter_id);
CREATE INDEX idx_incidents_assignee    ON incidents(assigned_to_id);
CREATE INDEX idx_incidents_status      ON incidents(status);
CREATE INDEX idx_incidents_created_at  ON incidents(created_at DESC);
