-- =====================================================================
--  V3: audit_log table
-- ---------------------------------------------------------------------
--  Mirrors hr.zavrsni.incidentapp.audit.AuditLog.
--
--  Why no foreign key on incident_id?
--    The audit trail must survive even if an incident row is hard-deleted
--    in the future (e.g. data-retention purge). Storing the incident id as
--    a plain BIGINT keeps the historical record intact and matches the
--    entity definition (no @ManyToOne/@JoinColumn on this field).
--
--  Index on incident_id supports the common query
--    "show me the audit trail for incident N" (newest first via occurred_at).
-- =====================================================================
CREATE TABLE audit_log (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    actor_username  VARCHAR(64)              NOT NULL,
    action          VARCHAR(24)              NOT NULL,
    incident_id     BIGINT                   NOT NULL,
    detail          TEXT,
    occurred_at     TIMESTAMP WITH TIME ZONE NOT NULL
);

CREATE INDEX idx_audit_log_incident      ON audit_log(incident_id);
CREATE INDEX idx_audit_log_occurred_at   ON audit_log(occurred_at DESC);
