-- =====================================================================
--  V4: comments table
-- ---------------------------------------------------------------------
--  Mirrors hr.zavrsni.incidentapp.comment.Comment.
--
--  Foreign keys:
--    author_id   -> users(id),     NOT NULL.
--    incident_id -> incidents(id), NOT NULL.
--
--  ON DELETE behaviour:
--    CASCADE on incident_id — if an incident is ever hard-deleted, its
--                             comments go with it (orphan comments would
--                             be meaningless).
--    RESTRICT on author_id  — preserve the link to the author; protect
--                             against accidentally deleting a user that
--                             has authored discussion.
--
--  Index on incident_id supports loading the comment thread for one
--  incident; sort by created_at on read.
-- =====================================================================
CREATE TABLE comments (
    id           BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    body         TEXT                     NOT NULL,
    author_id    BIGINT                   NOT NULL,
    incident_id  BIGINT                   NOT NULL,
    created_at   TIMESTAMP WITH TIME ZONE NOT NULL,

    CONSTRAINT fk_comments_author
        FOREIGN KEY (author_id)   REFERENCES users(id)     ON DELETE RESTRICT,
    CONSTRAINT fk_comments_incident
        FOREIGN KEY (incident_id) REFERENCES incidents(id) ON DELETE CASCADE
);

CREATE INDEX idx_comments_incident   ON comments(incident_id);
CREATE INDEX idx_comments_author     ON comments(author_id);
